### ISSUE TITLE
[eve7] Plugins.rb exists before set-up interview

### ISSUE THREAD

**Issue by Namasteh** [Namasteh/Eve-Bot#87]
Eve.rb:52:in `const_get': uninitialized constant Cinch::Plugins::EveMotion (NameError)
	from Eve.rb:52:in `block (3 levels) in <main>'
	from Eve.rb:51:in `each_line'
	from Eve.rb:51:in `block (2 levels) in <main>'
	from /home/marklar/.rvm/gems/ruby-2.2.1/gems/cinch-2.2.6/lib/cinch/bot.rb:218:in `configure'
	from Eve.rb:35:in `block in <main>'
	from /home/marklar/.rvm/gems/ruby-2.2.1/gems/cinch-2.2.6/lib/cinch/bot.rb:355:in `instance_eval'
	from /home/marklar/.rvm/gems/ruby-2.2.1/gems/cinch-2.2.6/lib/cinch/bot.rb:355:in `initialize'
	from Eve.rb:34:in `new'
	from Eve.rb:34:in `<main>'

**Comment by Namasteh** [comment]
Fixed in latest release.
